/*
  Input: k listHashingFile L B

  The list_hash files are generated by assignAll.c. For each k-mer x,
  the loaded hash value is a list of pairs (c, d) where c is 
  (the index of) a center and edit(x, c)=d. The list is sorted by d,
  break ties with c.

  Let d=4.
  Generata N pairs of k-mers with edit distance d. For a pair (s, t), 
  distinguish three cases
  i) s differs from t by 4 substituitions (exactly 4 mismatches)
  ii) s differs from t by 2 substituitions and 1 indel (more than 4 mismatches,
  exists a mismatch that if changed would result in edit=3)
  iii) s differs from t by 2 indels (more than 4 mismatches, no mismatch can
  be changed to make edit=3).

  For each case, s and t are said to have a collision if they share a
  center. Show the chances of each case and the collision probability for
  each case.

  By: Ke@PSU
  Last edited: 02/02/2022
*/

#include "util.h"
#include "AVLTree.h"
#include <time.h>
#include <string.h>

#define N 100000


typedef struct{
    int len;
    int total;
    size_t* centers;
}HashList;


void readHashFromFile(char* hash_file, int k, HashList* h, size_t n){
    FILE* fin = fopen(hash_file, "r");

    char* line = NULL;
    size_t len;

    size_t i, j;
    int size;
    
    
    for(i=0; i<n; i+=1){
	getdelim(&line, &len, ' ', fin); //kmer
	getdelim(&line, &len, ' ', fin); //ct
	size = atoi(line);
	h[i].len = size;
	h[i].centers = malloc_harder(sizeof *(h[i].centers) * size);

	for(j=0; j<size-1; j+=1){
	    getdelim(&line, &len, ' ', fin); //center_idx
	    h[i].centers[j] = atol(line);
	    getdelim(&line, &len, ' ', fin); //dist
	}
	getdelim(&line, &len, ' ', fin); //center_idx
	h[i].centers[j] = atol(line);
	getdelim(&line, &len, '\n', fin); //dist
    }
    
    fclose(fin);
    free(line);
}

int shareCenter(kmer s, kmer t, HashList* h){
    int i, j;
    int ls = h[s].len;
    size_t* cs = h[s].centers;
    int lt = h[t].len;
    size_t* ct = h[t].centers;

    for(i=0; i<ls; i+=1){
	for(j=0; j<lt; j+=1){
	    if(cs[i] == ct[j]){
		return 1;
	    }
	}
    }

    return 0;
}

//see beginning comment for details
int getEditType(kmer s, kmer t, int k){
    int i, ct=0, hasSub=0;
    kmer new_s, mask=3lu;
    for(i=0; i<k; i+=1){
	if((s&mask) != (t&mask)){
	    ct += 1;
	    if(!hasSub){
		new_s = (s&~mask)|(t&mask);
		if(editDist2(new_s, k, t, k, -1) == 3) hasSub = 1;
	    }
	}
	mask <<= 2;
    }
    if(hasSub){
	if(ct==4) return 0; //4 subs
	else return 1; //2 subs 1 indel
    }else return 2;//2 indels
}

int cmpCenters(const void* a, const void* b){
    long x = (long) a;
    long y = (long) b;
    long r = x-y;
    if(r<0) return -1;
    else if(r>0) return 1;
    else return 0;
}

//0-no center, 1-one center, 2-two centers
int getCenterType(kmer s, kmer t, AVLNode* ctree){
    int ct = 0;
    AVLNode* node = AVLSearch(ctree, (void*)s, cmpCenters);
    if(node) ct += 1;
    node = AVLSearch(ctree, (void*)t, cmpCenters);
    if(node) ct += 1;
    return ct;
}

int main(int argc, char* argv[]){
    if(argc != 4){
	printf("usage: centerListLSHDist4.out k listHashingFile centersFile\n");
	return 1;
    }

    int k = atoi(argv[1]);
    char* hash_file = argv[2];
    char* centers_file = argv[3];

    size_t NUM_KMERS = 1<<(k<<1);
    HashList* h = malloc_harder(sizeof *h *NUM_KMERS);
    readHashFromFile(hash_file, k, h, NUM_KMERS);

    srand(time(0));
    
    size_t i, j;
    kmer s, t;
    int share_center[3][3] = {{0, 0, 0}, {0, 0, 0}, {0, 0, 0}};
    int ct[3][3] = {{0, 0, 0}, {0, 0, 0}, {0, 0, 0}};
    int edit_type, center_type;

    size_t NUM_CENTERS;
    kmer* centers = readCentersFromFile(centers_file, k, &NUM_CENTERS);
    AVLNode* ctree = NULL;
    for(i=0; i<NUM_CENTERS; i+=1){
	ctree = AVLAdd(ctree, (void*)(centers[i]), cmpCenters);
    }
    free(centers);
    
    i=4;
    printf("edit_type center_type # #sha\n");
    for(j=0; j<N; j+=1){
	s = randomKMer(k);
	t = randomEdit(s, k, i);

	edit_type = getEditType(s, t, k);
	center_type = getCenterType(s, t, ctree);
	ct[edit_type][center_type] += 1;
	
	if(shareCenter(s, t, h)){
	    share_center[edit_type][center_type] += 1;
	}
    }

    for(i=0; i<3; i+=1){
	for(j=0; j<3; j+=1){
	    printf("%zu %zu %d %d %.2f%%\n",
		   i, j, ct[i][j], share_center[i][j],
		   share_center[i][j]*100.0/ct[i][j]);
	}
    }
    

    for(i=0; i<NUM_KMERS; i+=1){
	free(h[i].centers);
    }
    free(h);
    AVLFreeTree(ctree, NULL);
    
    return 0;
}
